const ROUTES = {
  LOGIN: "/",
  HOME: "/HOME",
  BASIC_DATA_FORM: "/CREATE-USER",
  CLINICALHISTORY: "/CREATE-CLINICAL-HISTORY",
  MONITORING: "/TRACKING-SESION",
  BASIC_DATA_EDITING: "/DATA-EDITING",
  INFORMS: "/INFORMS-CLINICAL-HISTORY",
  SEGMENTATION: "/SEGMENTATION",
  VARIOUS: "/VARIOUS",
  SETTINGS: "/SETTINGS",

};

export default ROUTES;
