const ROUTES = {
  LOGIN: "/",
  HOME: "/HOMEPAGE",
  BASIC_DATA_FORM: "/CREATEUSER",
  CLINICALHISTORY: "/CREATE-CLINICAL-HISTORY",
  MONITORING: "/CREATE-TRACKING-SESION",
  BASIC_DATA_EDITING: "/PATCBASICDATA",
  INFORMS: "/INFORMS-CLINICAL-HISTORY",
  SETTINGS: "/SETTINGS",

};

export default ROUTES;
