const ROUTES = {
  LOGIN: "/",
  HOME: "/HOMEPAGE",
  BASIC_DATA_FORM: "/BASICDATAFORM",
  CLINICALHISTORY: "/CLINICALHISTORY",
  MONITORING: "/TRACKING",
  INFORMS: "/INFORMS-CH",
  BASIC_DATA_EDITING: "/PATCBASICDATA",
  SETTINGS: "/SETTINGS",

};

export default ROUTES;
