import Navbar from "../Navbar/Navbar";
import styles from "./Segmentation.module.css";


const Segmentation = () => {
  return (
    <>
    <Navbar />
      <div className={styles.containerSegmentation}>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation
         👋🏽👋🏽👋🏽 Hola, soy el componente llamado Segmentation<br/>

      </div>
    </>
  );
};

export default Segmentation;